phpException:
  level: error

specialFunctions:
  - "__construct"
  - "__destruct"
  - "__call"
  - "__get"
  - "__set"
  - "__isset"
  - "__unset"
  - "__sleep"
  - "__wakeup"
  - "__toString"
  - "__set_state"
  - "__clone"
  - "__autoload"
  - "__invoke"

systemVariables:
  - "$this"
  - "$_GET"
  - "$_POST"
  - "$_FILES"
  - "$_COOKIE"
  - "$_SESSION"
  - "$_ENV"
  - "$_SERVER"
  - "$_REQUEST"
  - "$HTTP_GET_VARS"
  - "$HTTP_POST_VARS"
  - "$HTTP_COOKIE_VARS"
  - "$HTTP_SERVER_VARS"
  - "$HTTP_ENV_VARS"
  - "$HTTP_SESSION_VARS"

indentation:
  type: tabs
  number: 4
